import Key from "./Key";
import { KeyEnum } from "../lib/utils";

interface KeyboardProps {
  onKeydown?: (key: string) => void;
}

export default function Keyboard({ onKeydown }: KeyboardProps) {
  return (
    <div className="flex flex-col gap-3 items-center scale-[55%] md:scale-100 p-4">
      <div className="flex gap-2 w-max">
        <Key
          keyEnum={KeyEnum.Q}
          keyElement="Q"
          longVariant={false}
          onKeydown={onKeydown}
        />
        <Key
          keyEnum={KeyEnum.W}
          keyElement="W"
          longVariant={false}
          onKeydown={onKeydown}
        />
        <Key
          keyEnum={KeyEnum.E}
          keyElement="E"
          longVariant={false}
          onKeydown={onKeydown}
        />
        <Key
          keyEnum={KeyEnum.R}
          keyElement="R"
          longVariant={false}
          onKeydown={onKeydown}
        />
        <Key
          keyEnum={KeyEnum.T}
          keyElement="T"
          longVariant={false}
          onKeydown={onKeydown}
        />
        <Key
          keyEnum={KeyEnum.Y}
          keyElement="Y"
          longVariant={false}
          onKeydown={onKeydown}
        />
        <Key
          keyEnum={KeyEnum.U}
          keyElement="U"
          longVariant={false}
          onKeydown={onKeydown}
        />
        <Key
          keyEnum={KeyEnum.I}
          keyElement="I"
          longVariant={false}
          onKeydown={onKeydown}
        />
        <Key
          keyEnum={KeyEnum.O}
          keyElement="O"
          longVariant={false}
          onKeydown={onKeydown}
        />
        <Key
          keyEnum={KeyEnum.P}
          keyElement="P"
          longVariant={false}
          onKeydown={onKeydown}
        />
      </div>
      <div className="flex gap-2 w-max">
        <Key
          keyEnum={KeyEnum.A}
          keyElement="A"
          longVariant={false}
          onKeydown={onKeydown}
        />
        <Key
          keyEnum={KeyEnum.S}
          keyElement="S"
          longVariant={false}
          onKeydown={onKeydown}
        />
        <Key
          keyEnum={KeyEnum.D}
          keyElement="D"
          longVariant={false}
          onKeydown={onKeydown}
        />
        <Key
          keyEnum={KeyEnum.F}
          keyElement="F"
          longVariant={false}
          onKeydown={onKeydown}
        />
        <Key
          keyEnum={KeyEnum.G}
          keyElement="G"
          longVariant={false}
          onKeydown={onKeydown}
        />
        <Key
          keyEnum={KeyEnum.H}
          keyElement="H"
          longVariant={false}
          onKeydown={onKeydown}
        />
        <Key
          keyEnum={KeyEnum.J}
          keyElement="J"
          longVariant={false}
          onKeydown={onKeydown}
        />
        <Key
          keyEnum={KeyEnum.K}
          keyElement="K"
          longVariant={false}
          onKeydown={onKeydown}
        />
        <Key
          keyEnum={KeyEnum.L}
          keyElement="L"
          longVariant={false}
          onKeydown={onKeydown}
        />
      </div>
      <div className="flex gap-2 w-max">
        <Key
          keyEnum={KeyEnum.ENTER}
          keyElement="ENTER"
          longVariant={true}
          onKeydown={onKeydown}
        />
        <Key
          keyEnum={KeyEnum.Z}
          keyElement="Z"
          longVariant={false}
          onKeydown={onKeydown}
        />
        <Key
          keyEnum={KeyEnum.X}
          keyElement="X"
          longVariant={false}
          onKeydown={onKeydown}
        />
        <Key
          keyEnum={KeyEnum.C}
          keyElement="C"
          longVariant={false}
          onKeydown={onKeydown}
        />
        <Key
          keyEnum={KeyEnum.V}
          keyElement="V"
          longVariant={false}
          onKeydown={onKeydown}
        />
        <Key
          keyEnum={KeyEnum.B}
          keyElement="B"
          longVariant={false}
          onKeydown={onKeydown}
        />
        <Key
          keyEnum={KeyEnum.N}
          keyElement="N"
          longVariant={false}
          onKeydown={onKeydown}
        />
        <Key
          keyEnum={KeyEnum.M}
          keyElement="M"
          longVariant={false}
          onKeydown={onKeydown}
        />
        <Key
          keyEnum={KeyEnum.BACKSPACE}
          keyElement={
            <svg width="27" height="27" viewBox="0 0 27 27">
              <path
                fill="white"
                d="M22 3H7c-.69 0-1.23.35-1.59.88L0 12l5.41 8.11c.36.53.9.89 1.59.89h15c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zm0 16H7.07L2.4 12l4.66-7H22v14zm-11.59-2L14 13.41 17.59 17 19 15.59 15.41 12 19 8.41 17.59 7 14 10.59 10.41 7 9 8.41 12.59 12 9 15.59z"
              ></path>
            </svg>
          }
          longVariant={true}
          onKeydown={onKeydown}
        />
      </div>
    </div>
  );
}
